# Generated by Django 5.2.4 on 2025-07-06 03:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0002_usuario_is_active_usuario_is_staff_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_entrega', models.DateField()),
                ('archivo', models.FileField(blank=True, null=True, upload_to='actividades/')),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grado', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='NivelEducativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EntregaActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_entregado', models.FileField(upload_to='entregas/')),
                ('calificacion', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('actividad_asignada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brain.actividad')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignatura', models.CharField(max_length=50)),
                ('area_asignada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brain.area')),
                ('grado_asignado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brain.grado')),
            ],
        ),
        migrations.AddField(
            model_name='grado',
            name='nivel_educativo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brain.niveleducativo'),
        ),
        migrations.CreateModel(
            name='PlanDeLeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_leccion', models.CharField(max_length=40)),
                ('archivo_plan', models.FileField(upload_to='planesDeLeccion/')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brain.area')),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brain.asignatura')),
            ],
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(max_length=50, unique=True)),
                ('asignatura_asignada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brain.asignatura')),
            ],
        ),
        migrations.AddField(
            model_name='actividad',
            name='tema_asignado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brain.tema'),
        ),
    ]
