# Generated by Django 5.2.4 on 2025-07-07 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0003_actividad_area_grado_niveleducativo_entregaactividad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(max_length=10)),
                ('grado_asignado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brain.grado', unique=True)),
            ],
        ),
    ]
