# Generated by Django 5.2.4 on 2025-07-14 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0004_grupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='grado_asignado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brain.grado'),
        ),
    ]
