# Generated by Django 5.2.4 on 2025-07-15 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0005_alter_grupo_grado_asignado'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='grupo',
            unique_together={('grado_asignado', 'grupo')},
        ),
    ]
