# Generated by Django 5.2.4 on 2025-07-15 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0006_alter_grupo_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plandeleccion',
            name='archivo_plan',
            field=models.FileField(blank=True, null=True, upload_to='planesDeLeccion/'),
        ),
        migrations.AlterField(
            model_name='tema',
            name='tema',
            field=models.CharField(max_length=50),
        ),
    ]
