# Generated by Django 5.2.4 on 2025-07-15 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0007_alter_plandeleccion_archivo_plan_alter_tema_tema'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plandeleccion',
            name='asignatura',
        ),
        migrations.AddField(
            model_name='plandeleccion',
            name='tema',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='brain.tema'),
            preserve_default=False,
        ),
    ]
