# Generated by Django 5.2.4 on 2025-07-15 23:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0008_remove_plandeleccion_asignatura_plandeleccion_tema'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignaturas', models.ManyToManyField(to='brain.asignatura')),
                ('docente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('grado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brain.grado')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brain.grupo')),
            ],
        ),
    ]
