# Generated by Django 5.2.4 on 2025-07-25 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0010_remove_aula_docente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tema',
            name='asignatura_asignada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temas', to='brain.asignatura'),
        ),
    ]
