# Generated by Django 5.2.4 on 2025-08-01 01:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0011_alter_tema_asignatura_asignada'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignarDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brain.asignatura')),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brain.aula')),
                ('docente', models.ForeignKey(limit_choices_to={'rol': 'docente'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('asignatura', 'aula')},
            },
        ),
    ]
