# Generated by Django 5.2.4 on 2025-08-01 03:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0012_asignardocente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignardocente',
            name='docente',
            field=models.ForeignKey(limit_choices_to={'rol__rol': 'Docente'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
