# Generated by Django 5.2.4 on 2025-08-25 21:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0013_alter_asignardocente_docente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='HojaDeVidaDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_contacto_1', models.CharField(blank=True, max_length=15)),
                ('numero_contacto_2', models.CharField(blank=True, max_length=15)),
                ('direccion_residencia_1', models.CharField(blank=True, max_length=100)),
                ('direccion_residencia_2', models.CharField(blank=True, max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('formacion_academica', models.TextField(blank=True)),
                ('formacion_profesional', models.TextField(blank=True)),
                ('formacion_adicional', models.TextField(blank=True)),
                ('experiencia_en_el_cargo', models.TextField(blank=True)),
                ('nivel_educativo_especializa', models.TextField(blank=True)),
                ('municipo_expedicion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='brain.ciudad')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hoja_de_vida', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
