# Generated by Django 5.2.4 on 2025-08-25 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0014_alter_usuario_is_active_hojadevidadocente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hojadevidadocente',
            old_name='municipo_expedicion',
            new_name='municipio_expedicion',
        ),
    ]
