# Generated by Django 5.2.4 on 2025-08-26 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0015_rename_municipo_expedicion_hojadevidadocente_municipio_expedicion'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='primer_apellido',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='primer_nombre',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='segundo_apellido',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='segundo_nombre',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
